[package]
name = "number_guessing_game"
version = "0.1.0"
authors = ["Ville-Matti Hakanpää <villematti@villematti.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
